title: Judson Vital
logo: "images/judson.png" 
description: > 
  Sou aluno do curso técnico integrado em informática do IFRN Campus João Câmara.  
  <br><br>
  Tenho interesse em Tecnologia da Informação, Engenharia de Computação e afins. 
  <br><br>
  <a href="https://www.instagram.com/vitaljudson">Veja meu perfil no Instagram</a> 
  
theme: jekyll-theme-minimal

